name: iv_project_web_data
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_model:
    git:
      url: https://github.com/faequl96/iv_project_model.git
      ref: 0.1.1

  iv_project_core:
    git:
      url: https://github.com/faequl96/iv_project_core.git
      ref: 0.0.9+1

  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
